trunk/ventasnorte/caja/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('',
    url(r'^combo_dependiente/$', 'caja.views.combo_dependiente_autos', name='combo_mm_caja'),
    url(r'^crear_ccasa/$', 'ventasnorte.caja.views.crear_ccasa', name='crear_ccasa'),
    url(r'^crear_cauto/$', 'ventasnorte.caja.views.crear_cauto', name='crear_cauto'),
    url(r'^panel/$', 'ventasnorte.caja.views.panel', name='panel_caja'),
    url(r'^review_casa/(?P<casa_id>\d+)/$', 'ventasnorte.caja.views.review_casa', name='review_casa'),
    url(r'^review_auto/(?P<auto_id>\d+)/$', 'ventasnorte.caja.views.review_auto', name='review_auto'),
    url(r'^agregar_fotos_casa/(?P<casa_id>\d+)/$', 'ventasnorte.caja.views.agregar_fotos_casa', name='fotos_casa'),
    url(r'^agregar_fotos_auto/(?P<auto_id>\d+)/$', 'ventasnorte.caja.views.agregar_fotos_auto', name='fotos_auto'),
    url(r'^eliminar_foto_casa/(?P<foto_id>\d+)/$', 'ventasnorte.caja.views.eliminar_foto_casa', name='rmfotos_casa'),
    url(r'^eliminar_foto_auto/(?P<foto_id>\d+)/$', 'ventasnorte.caja.views.eliminar_foto_auto', name='rmfotos_auto'),
    url(r'^prin_foto_casa/(?P<foto_id>\d+)/$', 'ventasnorte.caja.views.foto_prin_casa', name='prfotos_casa'),
    url(r'^prin_foto_auto/(?P<foto_id>\d+)/$', 'ventasnorte.caja.views.foto_prin_auto', name='prfotos_auto'),


    url(r'^editar_casa/(?P<casa_id>\d+)/$', 'ventasnorte.caja.views.editar_casa', name='editar_casa'),
    url(r'^editar_auto/(?P<auto_id>\d+)/$', 'ventasnorte.caja.views.editar_auto', name='editar_auto'),
    url(r'^registro_usuario/$', 'ventasnorte.caja.views.registrar_usuario', name='registro_usuario'),    
    url(r'^mostrar/$', 'ventasnorte.caja.views.mostrar_usuario', name='mostrar_usuario'),
    url(r'^usuarios/consultar/$', 'ventasnorte.caja.views.usuarios_consultar', name='mostrar_usuario'),
    url(r'^modificaciones/$', 'ventasnorte.caja.views.modificaciones', name='modificaciones'),
    url(r'^modificaciones/id_search/$', 'ventasnorte.caja.views.id_search', name='modif_id_search'),
    url(r'^modificaciones/name_search/$', 'ventasnorte.caja.views.name_search', name='modif_name_search'),
    url(r'^detalle_usuario/(?P<user_id>\d+)/$', 'ventasnorte.caja.views.detalle_usuario', name='detalle_usuario'),

    url(r'^venta_casa/(?P<casa_id>\d+)/$', 'ventasnorte.caja.views.venta_casa', name='venta_casa'),
    url(r'^venta_auto/(?P<auto_id>\d+)/$', 'ventasnorte.caja.views.venta_auto', name='venta_auto'),
    url(r'^mostrar_ticket/(?P<venta_id>\d+)/$', 'ventasnorte.caja.views.display_ticket', name='ticket'),
    url(r'^consultar_paquete/$', 'ventasnorte.caja.views.paquetes_consultar', name='consultar_paquetes'),
)

trunk/ventasnorte/urls.py
from django.conf.urls.defaults import patterns, include, url
from settings import MEDIA_ROOT

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'ventasnorte.views.index', name='index'),
    url(r'^usuarios/', include('users.urls')),
    url(r'^caja/', include('caja.urls')),
    url(r'^casas/', include('clasificados.urls_casas')),
    url(r'^autos/', include('clasificados.urls_autos')),
    url(r'^lugares/', include('lugares.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('django.views',(r'^media/(?P<path>.*)$', 'static.serve', {'document_root': MEDIA_ROOT}))

trunk/ventasnorte/caja/models.py
from django.db import models
from clasificados.models import ClasifCasa, ClasifAuto, Paquete
# Create your models here.
TIPO_CHOICES = ((1,'Auto'), (2,'Casa'))

class Venta(models.Model):
    paquete=models.ForeignKey(Paquete)
    nombre_paquete = models.CharField(max_length=30)    

    precio_paquete = models.DecimalField(max_digits=10, decimal_places=2)
    precio_prioridad = models.DecimalField(max_digits=10, decimal_places=2)
    precio_foto = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Precio de foto extra")
    precio_texto = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Precio de texto extra")

    fotos_extra = models.IntegerField()
    texto_extra = models.BooleanField()
    prioridad = models.BooleanField()

    min_texto = models.IntegerField()
    min_fotos = models.IntegerField()

    total = models.DecimalField(max_digits=9, decimal_places=2)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    tipo = models.PositiveSmallIntegerField()
    auto = models.ForeignKey(ClasifAuto, blank=True, null=True)
    casa = models.ForeignKey(ClasifCasa, blank=True, null=True)

    def __unicode__(self):
        return "%s - %s" % (self.id, self.nombre_paquete)

    def get_importe_foto(self):
        importe = self.fotos_extra * self.precio_foto
        return importe

    def get_clasificado(self):
        if self.tipo == 1:
            return self.auto
        else:
            return self.casa

trunk/ventasnorte/clasificados/models.py
# coding: latin1
from django.db import models
from django.db.models import Q
from lugares.models import Estado, Municipio
from django.contrib import admin
from django.contrib.auth.models import User
from PIL import Image
import datetime
from django.template.defaultfilters import slugify

DISPO_DICT = [{'nombre':'En Venta','slug':'venta', 'id':1}, {'nombre':'En Renta','slug':'renta','id':2}, {'nombre':'Traspaso','slug':'traspaso','id':3}]

MONEDA_CHOICES = ((1, 'Pesos'),(2,'Dolares'))
CONDICION_CASA_CHOICES = ((1, 'Excelente'),(2,'Buena'),(3,'Regular'))
CONDICION_AUTO_CHOICES = ((1, 'Excelente'),(2,'Buena'),(3,'Regular'), (4,'Chocado'))
DISPO_CHOICES = ((1, 'Venta'),(2, 'Renta'),(3, 'Traspaso'))
TRANSMISION_CHOICES = ((1,'Standard'),(2,'Automatico'))
COMBUST_CHOICES = ((1, 'Gasolina'),(2,'Diesel'))
STATUS_CHOICES = ((0,'Activo'), (1, 'Vendido'), (2,'Reactivado'), (3,'Pendiente'))
NACION_CHOICES = ((1,'Mexicano'),(2,'Regularizado'),(3,'Americano'))

IMG_NOT_AVAILABLE_CASA = "/img/no_disponible_casa.png"
IMG_NOT_AVAILABLE_AUTO = "/img/no_disponible_auto.png"

class Paquete(models.Model):
    nombre = models.CharField(max_length=30, unique=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    dias_activo = models.IntegerField()
    min_fotos = models.IntegerField()
    min_texto = models.IntegerField(help_text="Numero de caracteres minimos.")
    foto_extra = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Precio de foto extra")
    texto_extra = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Precio de texto extra")
    prioridad = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Precio de prioridad")
    def __unicode__(self):
        return self.nombre

class PaqueteAdmin(admin.ModelAdmin):
    list_display = ('nombre','precio', 'min_fotos','min_texto','foto_extra','texto_extra')

try:
    admin.site.register(Paquete,PaqueteAdmin)
except:
    pass

class CategoriaCasa(models.Model):
    nombre = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(editable=False, unique=True)
    def __unicode__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        self.slug= slugify(self.nombre)
        super(CategoriaCasa, self).save(*args, **kwargs)

    def clasif_count(self):
        return self.clasifcasa_set.filter(status=0).count()

try:
    admin.site.register(CategoriaCasa)
except:
    pass


class CasaActivesManager(models.Manager):
    def get_query_set(self):
        hoy = datetime.date.today()
        return super(CasaActivesManager, self).get_query_set().filter(status=0, fecha_inicio__lte=hoy, fecha_fin__gte=hoy).order_by('-prioridad')



class ClasifCasa(models.Model):
    user = models.ForeignKey(User)
    titulo=models.CharField(max_length=70)
    paquete=models.ForeignKey(Paquete, blank=False, default='')
    precio=models.DecimalField(max_digits=12,decimal_places=2, null=True, blank=True, verbose_name="Precio de Casa")
    moneda=models.PositiveSmallIntegerField(choices=MONEDA_CHOICES, null=True, blank=True)
    disponibilidad=models.PositiveSmallIntegerField(choices=DISPO_CHOICES)
    categoria_casa = models.ForeignKey(CategoriaCasa, verbose_name="Categoria")

    estado=models.ForeignKey(Estado,blank=False, default='')
    municipio=models.ForeignKey(Municipio,blank=False, default='')
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, default=0)

    domicilio=models.CharField(max_length=200, null=True, blank=True)
    colonia=models.CharField(max_length=70, null=True, blank=True)
    codigo_postal=models.IntegerField(null=True, blank=True)
    referencia=models.CharField(max_length=70, null=True, blank=True)#TODO Estara bien este?
    condicion=models.PositiveSmallIntegerField(choices=CONDICION_CASA_CHOICES)
    pisos=models.IntegerField()
    superficie=models.CharField(max_length=15, null=True, blank=True)#TODO Estara bien este?
    recamaras=models.IntegerField(null=True, blank=True)#TODO Estara bien este?
    banos=models.IntegerField(null=True, blank=True)#TODO Estara bien este?
    descripcion=models.TextField(null=True, blank=True)
    prioridad = models.BooleanField(help_text="Cargo extra por presencia en pagina principal.")
    usuario_creador = models.ForeignKey(User, related_name="creadorcasa_set")
    fecha_inicio=models.DateField()
    fecha_fin=models.DateField()
    fecha_creacion=models.DateTimeField(auto_now_add=True)
    fecha_modificacion=models.DateTimeField(auto_now=True)
    
    #Informacion de usuario
    email=models.EmailField(max_length=75, null=True, blank=True)
    telefono=models.CharField(max_length=30, null=True, blank=True)
    celular=models.CharField(max_length=30, null=True, blank=True)
    direccion=models.TextField(null=True, blank=True)
    objects = models.Manager()
    get_actives = CasaActivesManager()

    def __unicode__(self):
        return "%s CASA" % self.id

    def foto_count(self):
        count = self.fotocasa_set.all().count()
        return count

    def get_precio(self):
        if self.precio == None:
            precio = "A tratar"
        else:
            precio=self.precio
        return precio

    def get_dispo_slug(self):
        if self.disponibilidad==1:
            return 'venta'
        elif self.disponibilidad==2:
            return 'renta'
        else:
            return 'traspaso'

    def get_main_thumb_url(self):
        fotos = self.fotocasa_set.all()

        if fotos.count()>0:
            mains = fotos.filter(principal=True)
            if mains.count() > 0:
                main = mains[0]
            else:
                main = fotos[0]    
            print main.get_thumb_url()
            return main.get_thumb_url()

        else:
            return IMG_NOT_AVAILABLE_CASA

    def get_extra_photo_count(self):
        num_fotos_extra = self.foto_count() - self.paquete.min_fotos
        if num_fotos_extra < 0: 
            num_fotos_extra=0
        return num_fotos_extra

    def has_extra_text(self):
        if len(self.descripcion) > self.paquete.min_texto:
            return True
        else:
            return False
        
    def get_total(self):
        paquete = self.paquete
        p_paquete = paquete.precio
        p_fotosx = self.get_extra_photo_count() * paquete.foto_extra
        if self.has_extra_text():
            p_textox = paquete.texto_extra
        else:
            p_textox = 0
        if self.prioridad:
            p_priori = paquete.prioridad
        else:
            p_priori = 0
        total = p_paquete + p_fotosx + p_textox + p_priori
        return total

    def get_sliced_gallery(self):
        galeria = self.fotocasa_set.all()[:3]
        return galeria

class FotoCasa(models.Model):
    casa=models.ForeignKey(ClasifCasa)
    foto=models.ImageField(upload_to='clasif_casas', max_length=200)
    principal = models.BooleanField()
    

    def save(self):
        if self.principal:
            try:
                temp = FotoCasa.objects.get(principal=True, casa=self.casa)
                if self != temp:
                    temp.principal = False
                    temp.save()
            except FotoCasa.DoesNotExist:
                pass

        super(FotoCasa, self).save()
        if self.foto:
            self.thumb_img(self.foto)
            self.resize_img(self.foto)

    def get_thumb_url(self):
        if self.foto:
            baseurl=self.foto.url
            urlbase, format = baseurl.rsplit('.', 1)
            urlthumb = urlbase + '_T' + '.' +  format
            return urlthumb
        else:
            return "/media/no_disponible.jpeg"

    def resize_img(self, imagen):
        maxw=640
        maxh=640
        method= Image.ANTIALIAS
        w=imagen.width
        h=imagen.height
        path=imagen.path
        if h<=maxh or w<=maxw:
            pass
        else:
            pict= Image.open(path)


            imAspect=float(w)/float(h)
            outAspect=float(maxw)/float(maxh)

            if imAspect>=outAspect:
                img=pict.resize((maxw, int((float(maxw)/imAspect)+0.5)), method)
                img.save(path)
            else:
                img=pict.resize((int((float(maxh)*imAspect)+0.5),maxh),method)
                img.save(path)

    def thumb_img(self, imagen):
        maxw=128
        maxh=128
        method= Image.ANTIALIAS
        w=imagen.width
        h=imagen.height
        path=imagen.path

        pict= Image.open(path)

        nombase, format = path.rsplit('.', 1)

        nomthumb = nombase + '_T' + '.' +  format
	
        imAspect=float(w)/float(h)
        outAspect=float(maxw)/float(maxh)

        if imAspect>=outAspect:
            img=pict.resize((maxw, int((float(maxw)/imAspect)+0.5)), method)
            img.save(nomthumb)
        else:
            img=pict.resize((int((float(maxh)*imAspect)+0.5),maxh),method)
            img.save(nomthumb)


class MarcaAuto(models.Model):
    nombre=models.CharField(max_length=70, unique=True)
    logo = models.ImageField(upload_to="logos_auto", blank=True, null=True)
    fondo = models.ImageField(upload_to="fondos_auto", blank=True, null=True)
    slug = models.SlugField(editable=False, unique=True)
    
    def __unicode__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        self.slug= slugify(self.nombre)
        super(MarcaAuto, self).save(*args, **kwargs)

        if self.fondo:
            self.resize_img(self.fondo)
        if self.logo:
            self.resize_logo(self.logo)

    def resize_img(self, imagen):
        maxw=150
        maxh=150
        method= Image.ANTIALIAS
        w=imagen.width
        h=imagen.height
        path=imagen.path
        if h<=maxh or w<=maxw:
            pass
        else:
            pict= Image.open(path)


            imAspect=float(w)/float(h)
            outAspect=float(maxw)/float(maxh)

            if imAspect>=outAspect:

trunk/ventasnorte/caja/templates/crear_clasif_auto.html
{%extends "base.html"%}

{%block title%}
<title>Clasificado para automovil/vehiculo</title>
{%endblock%}

{%block maincontent%}
<div id="content">
    <a href="{%url caja.views.registrar_usuario%}" class="button blueb">Registrar nuevo usuario</a>
    <div id="form">
        <form method="POST">
            <input type="hidden" id="id_mintexto" value="140">
            {%csrf_token%}
            <table>
                {{form}}
            </table>
            <input type="submit" value="Guardar" class="button blueb">

    </div>
    <div id="userinfo_form">

            {%csrf_token%}
            <table>
                {{form2}}
            </table>
        </form>
    </div>

</div>
{%endblock%}

trunk/ventasnorte/caja/templates/crear_clasif_casa.html
{%extends "base.html"%}

{%block title%}
<title>Crearclasificado para casa/bienes inmuebles</title>
{%endblock%}


{%block maincontent%}
<div id="content">
    <a href="{%url caja.views.registrar_usuario%}" class="button blueb">Registrar nuevo usuario</a>
    <div id="form">
        <form method="POST">
            <input type="hidden" id="id_mintexto" value="140">
            {%csrf_token%}
            <table>
                {{form}}
            </table>
            <input type="submit" class="button blueb">
    </div>
    <div id="userinfo_form">

            {%csrf_token%}
            <table>
                {{form2}}
            </table>
        </form>
    </div>
</div>
{%endblock%}

trunk/ventasnorte/caja/templates/mostrar_usuario.html
{%extends "base.html"%}

{%block title%}
<title>Informacion de Usuario {{user.id}}</title>
{%endblock%}

{%block maincontent%}
<div id="content">
    <p>
        El usuario <span class="display_username">{{user.username}}</span> tiene el ID <span class="display_id">{{user.id}}</span>
    </p>

    <p>
    Y su contraseña es <span class="display_passwd">{{passwd}}</span>
    </p>
    <a class="blue" href="{%url caja.views.panel%}">regresar a panel
</div>
{%endblock%}

trunk/ventasnorte/caja/templates/panel.html
{%extends "base.html"%}

{%block maincontent%}
<div id="content">
    <ul class="blue">
        <li><a class="blue" href="{%url caja.views.registrar_usuario%}">Registrar un nuevo usuario</a></li>
        <li><a class="blue" href="{%url caja.views.crear_ccasa%}">Crear Clasificado de Casa/Bienes inmuebles</a></li>
        <li><a class="blue" href="{%url caja.views.crear_cauto%}">Crear Clasificado de Automovil o Vehiculo</a></li>
        <li><a class="blue" href="{%url caja.views.modificaciones%}">Modificaciones y Correcciones</a></li>

    </ul>
</div>
{%endblock%}

trunk/ventasnorte/caja/templates/registro_caja.html
{%extends "base.html"%}

{%block title%}
<title>Registro de Usuarios</title>
{%endblock%}

{%block maincontent%}
<div id="content">
    <div id="form">
        <form method="POST">
            {%csrf_token%}
            <table>
                {{form}}
            </table>
            <input type="submit" class="button blueb" value="Registrar Usuario">
        </form>
    </div>
</div>
{%endblock%}

trunk/ventasnorte/caja/templates/review_auto.html
{%extends "base.html"%}

{%block title%}
<title>Vista de Clasificado {{auto.id}}</title>
{%endblock%}


{%block maincontent%}
<div id="content">
    <h3 class="titulo">{{auto.titulo}}</h3>

<div class="photo_slot">
    <form method="POST" enctype="multipart/form-data" action="{%url caja.views.agregar_fotos_auto auto.id%}" accept="image/gif,image/jpeg,image/png,image/tiff">
        {%csrf_token%}
        <table>
            {{form}}
        </table>
        <input class="button blueb" type="submit" value="Agregar Fotos">
    </form>

</div>

<div class="photo_slot">
    {%for foto in auto.fotoauto_set.all%}
        {%if foto.principal%}
            <div class="imagerv fotoprin">
        {%else%}
            <div class="imagerv">
        {%endif%}

            <a href="/media/{{foto.foto.url}}"><img class="rvgallery" src="/media/{{foto.get_thumb_url}}" /></a>
            <br>
            <form method="POST" action="{%url caja.views.foto_prin_auto foto.id%}">
            {%csrf_token%}
            {%if foto.principal%}
                <input type="submit" value="Portada" class="button" disabled>
            {%else%}
                <input type="submit" value="Portada" class="button blueb">
            {%endif%}
            </form>
            <br>
            <form method="POST" action="{%url caja.views.eliminar_foto_auto foto.id%}">
            {%csrf_token%}
            <input type="submit" value="Eliminar" class="redbutton">
            </form>

        </div>
    {%endfor%}
</div>


    {{auto.pauqete.nombre}}
    <div class="topinfo">
        <table class="info_auto">
        {%if auto.precio%}
        <tr>
            <td>
               <span class="precio"> ${{auto.precio|floatformat:2}} {{auto.get_moneda_display}}</span>
            </td>
        </tr>
        {%endif%}

        <tr>
            <td>{{auto.marca}}, {{auto.modelo}}, {{auto.serie}}</td>
        </tr>
        <tr>
            <td>En {{auto.municipio}}, {{auto.estado}}</td>
        </tr>
        </table>
    </div>


    <p class="descripcion">
        {{auto.descripcion}}
    </p>


    <table class="dets_auto">
        <tr>
            <th>Condicion</th><th>Pasajeros</th>
        </tr>
        <tr>
            <td>{{auto.condicion}}</td>   <td>{{auto.pasajeros}}</td>
        </tr>
        <tr>
            <th>Color</th><th>Transmision</th>
        </tr>
        <tr>
            <td>{{auto.color}}</td><td>{{auto.transmision}}</td>
        </tr>
        <tr>
            <th>Puertas</th><th>Cilindros</th>
        </tr>
        <tr>
            <td>{{auto.puertas}}</td><td>{{auto.cilindros}}</td>
        </tr>
        <tr>
            <th>Combustible</th><th>Kilometraje</th>
        </tr>
        <tr>
            <td>{{auto.combustible}}</td><td>{{auto.kilometraje}}</td>
        </tr>

    </table>



<table class="contact_info">
    <tr>
        <th class="section_title" colspan="2">Informacion de Contacto</th>
    </tr>

    <tr>
        <th>Correo Electronico</th> <td>{{auto.email}}</td>
    </tr>

    <tr>
        <th>Telefono Fijo</th><td>{{auto.telefono}}</td>
    </tr>

    <tr>
        <th>Celular</th><td>{{auto.celular}}</td>
    </tr>

    <tr>
        <th>Direccion</th><td>{{auto.direccion}}</td>
    </tr>
</table>

<div id="controls">
    <a href="{%url caja.views.editar_auto auto.id%}" class="button orangeb fleft"> Regresar y editar </a>
    <form action="{%url caja.views.venta_auto auto.id%}" method="POST">
    {%csrf_token%}
    <input type="submit" class="button blueb fright" value="Confirmar">
    </form>
</div>



</div>
{%endblock%}

trunk/ventasnorte/caja/templates/review_casa.html
{%extends "base.html"%}

{%block title%}
<title>Vista de Clasificado {{casa.id}}</title>
{%endblock%}

{%block maincontent%}
<div id="content">
    <h3 class="titulo">{{casa.titulo}}</h3>
    <p>Activo desde hoy {{casa.fecha_inicio}} hasta el {{casa.fecha_fin}}.</p>
<div class="photo_slot">
    <form method="POST" enctype="multipart/form-data" action="{%url caja.views.agregar_fotos_casa casa.id%}">
        {%csrf_token%}
        <table>
            {{form}}
        </table>
        <input class="button blueb" type="submit" value="Agregar Fotos">
    </form>

</div>

<div class="photo_slot">
    {%for foto in casa.fotocasa_set.all%}
        {%if foto.principal%}
            <div class="imagerv fotoprin">
        {%else%}
            <div class="imagerv">
        {%endif%}
            <a href="/media/{{foto.foto.url}}"><img class="rvgallery" src="/media/{{foto.get_thumb_url}}" /></a>
            <br>
            <form method="POST" action="{%url caja.views.foto_prin_casa foto.id%}">
            {%csrf_token%}
            {%if foto.principal%}
                <input type="submit" value="Portada" class="button" disabled>
            {%else%}
                <input type="submit" value="Portada" class="button blueb">
            {%endif%}
            </form>
            <br>
            <form method="POST" action="{%url caja.views.eliminar_foto_casa foto.id%}">
            {%csrf_token%}
            <input type="submit" value="Eliminar" class="redbutton">
            </form>

        </div>
    {%endfor%}
</div>


    {{casa.pauqete.nombre}}
    <div class="topinfo">
        <table class="info_casa">
        {%if casa.precio%}
        <tr>
            <td>
               <span class="precio"> ${{casa.precio|floatformat:2}} {{casa.get_moneda_display}}</span>
            </td>
        </tr>
        {%endif%}

        <tr>
            <td>En {{casa.get_disponibilidad_display}}</td>
        </tr>
        <tr>
            <td>En {{casa.municipio}}, {{casa.estado}}</td>
        </tr>
        </table>
    </div>


    <p class="descripcion">
        {{casa.descripcion}}
    </p>

<div class="clear"></div>


<div class="casa_data">
        <table class="dets_casa">
            <tr>
                <th>Colonia<td>{{casa.colonia}}</td></th>
            </tr>

            <tr>
                <th>Codigo Postal</th><td>{{casa.codigo_postal}}</td>
            </tr>

            <tr>
                <th>Tamaño de Area</th><td>{{casa.superficie}}</td>
            </tr>

            <tr>
                <th>No. de Baños</th><td>{{casa.banos}}</td>
            </tr>

            <tr>
                <th>Domicilio</th><td>{{casa.domicilio}}</td>
            </tr>

        </table>
</div> 

<div class="casa_data">
        <table class="dets_casa">
            <tr>
                <th>Condicion</th><td>{{casa.get_condicion_display}}</td>
            </tr>
            <tr>
                <th>Referencia</th><td>{{casa.referencia}}</td>
            </tr>
                <th>Pisos</th><td>{{casa.pisos}}</td>
            <tr>
                <th>No. de Recamaras</th><td>{{casa.recamaras}}</td>
            </tr>           
        </table>

</div>


<table class="contact_info">
    <tr>
        <th class="section_title" colspan="2">Informacion de Contacto</th>
    </tr>

    <tr>
        <th>Correo Electronico</th> <td>{{casa.email}}</td>
    </tr>

    <tr>
        <th>Telefono Fijo</th><td>{{casa.telefono}}</td>
    </tr>

    <tr>
        <th>Celular</th><td>{{casa.celular}}</td>
    </tr>

    <tr>
        <th>Direccion</th><td>{{casa.direccion}}</td>
    </tr>
</table>

<div id="controls">
    <a href="{%url caja.views.editar_casa casa.id%}" class="button orangeb fleft"> Regresar y editar </a>

    <form method="POST" action="{%url caja.views.venta_casa casa.id%}">
    {%csrf_token%}
    <input type="submit" class="button blueb fright" value="Confirmar">
    </form>
</div>

</div>
{%endblock%}